name: sundog-mlcourse
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - matplotlib
  - tensorflow
  - scikit-learn==0.22
  - pydotplus
  - ipython
  - gym
  - scipy
  - pyspark
  - statsmodels
  